### ISSUE TITLE
Query CE02 Runs too long

### ISSUE THREAD

**Issue by bmosseveld** [EHDEN/QueryLibrary#11]
While testing the current status of the queries, query CE02 was running too long > 1 hr.
Sofar I didn't wait for it to finish. Is there a way to make it more simple. I suspect the JOINs to make it very slow.

**Comment by AnthonyMolinaro** [comment]
@bmosseveld, @PRijnbeek,

I just ran this on my end and it took 5.26 seconds.

Here's how you can diagnose it on your end:

1. Look at the cte hip_fracture:

WITH hip_fracture AS (
SELECT DISTINCT ca.descendant_concept_id 
  FROM concept c 
  JOIN concept_ancestor ca
    ON ca.ancestor_concept_id = c.concept_id 
 WHERE c.concept_code = '359817006'  
) 
  
How many rows does that return?   I get 45 on my system and a count returns in 1.86s.  Additionally, do you have an index on c.concept_code, c.concept_id, and ca.ancestor_concept_id?


2.  The joins to the other tables are straight forward and would only be slow if there are missing indices are millions of rows without corresponding hw resources (cpu and ram):

  FROM condition_era ce 
  JOIN hip_fracture hf  
    ON hf.descendant_concept_id = ce.condition_concept_id 
  JOIN person p
    ON p.person_id = ce.person_id 
  JOIN concept c 
    ON c.concept_id = p.gender_concept_id 

All those column that join should be indexed.

**Comment by bmosseveld** [comment]
@PRijnbeek Can we create indices in the SYNPUF database?

**Comment by PRijnbeek** [comment]
Sure you can run the sql to do that.

**Comment by bmosseveld** [comment]
Solved
