### ISSUE TITLE
Queries that use old CDM version

### ISSUE THREAD

**Issue by PRijnbeek** [EHDEN/QueryLibrary#12]
There are a few queries that are based on an old CDM version that contains columns that do not exist anymore:

SYNPUF | SQL Server | ./queries/drug/D12_Find_indications_for_a_drug.md | Error executing SQL:com.microsoft.sqlserver.jdbc.SQLServerException: Invalid column name 'concept_level'.An error report has been created at  D:/Documents/Github/QueryLibrary/inst/shinyApps/QueryLibrary/errorReport.txt | 0.124799967
-- | -- | -- | -- | --
SYNPUF | SQL Server | ./queries/drug/D13_Find_indications_as_condition_concepts_for_a_drug.md | Error executing SQL:com.microsoft.sqlserver.jdbc.SQLServerException: Invalid column name 'concept_level'.An error report has been created at  D:/Documents/Github/QueryLibrary/inst/shinyApps/QueryLibrary/errorReport.txt | 0.110200167
SYNPUF | SQL Server | ./queries/drug/D14_Find_drugs_for_an_indication.md | Syntactically correct | 0.07799983
SYNPUF | SQL Server | ./queries/drug/D15_Find_drugs_for_an_indication_provided_as_condition_concepts.md | Error executing SQL:com.microsoft.sqlserver.jdbc.SQLServerException: Invalid column name 'concept_level'.An error report has been created at  D:/Documents/Github/QueryLibrary/inst/shinyApps/QueryLibrary/errorReport.txt | 0.046799898
SYNPUF | SQL Server | ./queries/drug/D16_Find_drugs_for_an_indication_by_indication_type.md | Syntactically correct | 0.260601044
SYNPUF | SQL Server | ./queries/drug/D17_Find_ingredients_for_an_indication.md | Error executing SQL:com.microsoft.sqlserver.jdbc.SQLServerException: Invalid column name 'concept_level'.An error report has been created at  D:/Documents/Github/QueryLibrary/inst/shinyApps/QueryLibrary/errorReport.txt | 0.062400103
SYNPUF | SQL Server | ./queries/drug/D18_Find_ingredients_for_an_indication_provided_as_condition_concept.md | Error executing SQL:com.microsoft.sqlserver.jdbc.SQLServerException: Invalid column name 'concept_level'.An error report has been created at  D:/Documents/Github/QueryLibrary/inst/shinyApps/QueryLibrary/errorReport.txt | 0.046799898
SYNPUF | SQL Server | ./queries/drug/D19_Find_ingredients_for_an_indication_by_indication_type.md | Error executing SQL:com.microsoft.sqlserver.jdbc.SQLServerException: Invalid column name 'concept_level'.An error report has been created at  D:/Documents/Github/QueryLibrary/inst/shinyApps/QueryLibrary/errorReport.txt | 0.046800852
SYNPUF | SQL Server | ./queries/drug/D20_Find_dose_form_of_a_drug.md | Syntactically correct | 0.114200115
SYNPUF | SQL Server | ./queries/drug/D21_Find_route_of_administration_of_a_drug.md | Error executing SQL:com.microsoft.sqlserver.jdbc.SQLServerException: Invalid object name 'route'.An error report has been created at  D:/Documents/Github/QueryLibrary/inst/shinyApps/QueryLibrary/errorReport.txt | 0.031200171
SYNPUF | SQL Server | ./queries/drug/D22_Find_drugs_by_class_and_dose_form.md | Syntactically correct | 0.347600937
SYNPUF | SQL Server | ./queries/drug/D23_Find_drugs_by_class_and_route_of_administration.md | Error executing SQL:com.microsoft.sqlserver.jdbc.SQLServerException: Invalid object name 'route'.An error report has been created at  D:/Documents/Github/QueryLibrary/inst/shinyApps/QueryLibrary/errorReport.txt | 0.046800137

Anthony could have a look at these and decide if there are new ways do this or drop these?

**Comment by AnthonyMolinaro** [comment]
@PRijnbeek 

I've updated 14,15,17,18,19 by making minor changes (changing concept_id or commenting out a filter) and they work fine against synpuf on pdw.

Queries 16, 20, and 22 work fine against synpuf on pdw without any changes.

We should drop 21 and 23 as the route table no longer exists.

I'll work on 12 and 13 next week.

**Comment by AnthonyMolinaro** [comment]
@PRijnbeek 

Sorry for letting these last two linger.  We should drop 12 and 13 as there is no indication data in synpuf.  The following returns 0:

select count(*) from concept where vocabulary_id = 'Indication'

**Comment by PRijnbeek** [comment]
Thanks @AnthonyMolinaro i will discuss with @bmosseveld next week to clean up the list and do a next round of testing on all the DBMs systems. If all works well on the above queries we will close the issue.
