### ISSUE TITLE
Remaining issues The Hyve

### ISSUE THREAD

**Issue by bmosseveld** [EHDEN/QueryLibrary#13]
SQL   Server | Hyve | ./queries/drug_exposure/DEX26_Distribution_of_drug_exposure_end_dates.md | Error executing SQL:          com.microsoft.sqlserver.jdbc.SQLServerException: Arithmetic overflow error   converting expression to data type int.          An error report has been created at    D:/Documents/Github/QueryLibrary/inst/shinyApps/QueryLibrary/errorReport.txt
-- | -- | -- | --
SQL Server | Hyve | ./queries/drug_exposure/DEX27_Distribution_of_drug_exposure_start_dates.md | Error executing SQL:          com.microsoft.sqlserver.jdbc.SQLServerException: Arithmetic overflow error   converting expression to data type int.          An error report has been created at    D:/Documents/Github/QueryLibrary/inst/shinyApps/QueryLibrary/errorReport.txt
SQL   Server | Hyve | ./queries/obervation_period/OP11_Distribution_of_observation_period_end_dates.md | Error executing SQL:          com.microsoft.sqlserver.jdbc.SQLServerException: Arithmetic overflow error   converting expression to data type int.          An error report has been created at    D:/Documents/Github/QueryLibrary/inst/shinyApps/QueryLibrary/errorReport.txt
SQL   Server | Hyve | ./queries/obervation_period/OP13_Distribution_of_observation_period_start_dates.md | Error executing SQL:          com.microsoft.sqlserver.jdbc.SQLServerException: The function   'PERCENTILE_DISC' must have an OVER clause.          An error report has been created at    D:/Documents/Github/QueryLibrary/inst/shinyApps/QueryLibrary/errorReport.txt
SQL   Server | Hyve | ./queries/obervation_period/OP16_Count_of_genders_stratified_by_year_and_age_group.md | Error executing SQL:          com.microsoft.sqlserver.jdbc.SQLServerException: Incorrect syntax near   'USING'.          An error report has been created at    D:/Documents/Github/QueryLibrary/inst/shinyApps/QueryLibrary/errorReport.txt

Could you please fix this?

**Comment by PRijnbeek** [comment]
@MaximMoinat can you please fix these so we can move forward?

Thanks

**Comment by MaximMoinat** [comment]
Sorry for not coming back to this earlier. Thanks for fixing this @bmosseveld.

Tested the queries on our postgresql instance, and they all run successfully (after the very minor fix mentioned above). Issue can be closed.
