### ISSUE TITLE
Remaining issues Odysseus

### ISSUE THREAD

**Issue by bmosseveld** [EHDEN/QueryLibrary#14]
SQL   Server | ODYSSEUS | ./queries/drug_exposure/DEX03_Distribution_of_age_stratified_by_drug.md | Error executing SQL:          com.microsoft.sqlserver.jdbc.SQLServerException: The function   'PERCENTILE_DISC' must have an OVER clause.          An error report has been created at    D:/Documents/Github/QueryLibrary/inst/shinyApps/QueryLibrary/errorReport.txt
-- | -- | -- | --
SQL   Server | ODYSSEUS | ./queries/drug_exposure/DEX09_Distribution_of_distinct_drugs_per_person_over_some_time_period.md | Error executing SQL:          com.microsoft.sqlserver.jdbc.SQLServerException: The function   'PERCENTILE_DISC' must have an OVER clause.          An error report has been created at    D:/Documents/Github/QueryLibrary/inst/shinyApps/QueryLibrary/errorReport.txt

Could you please fix this?

**Comment by PRijnbeek** [comment]
@eldarallakhverdiiev can you please fix these so we can move forward thanks

**Comment by eldarallakhverdiiev** [comment]
Fixed it right now. 
The issues were related to https://github.com/EHDEN/QueryLibrary/issues/10

**Comment by PRijnbeek** [comment]
Great. @bmosseveld if you tested these queries can you close this issue afterwards.
