### ISSUE TITLE
README file mentions wrong function name

### ISSUE THREAD

**Issue by schuemie** [EHDEN/QueryLibrary#16]
The README mentions `QueryLibrary::launchQueryLibraryApp()`, but this should be `launchSqlLibrary()`

**Comment by PRijnbeek** [comment]
I would recommend we make it consistent with the application name and rename the function to "launchQueryLIbrary'. We should be consistent with other OHDSI webapp launch function names, e.g. SqlRenderDeveloper uses launchSqlRenderDeveloper.

@bmosseveld can you make this change

**Comment by bmosseveld** [comment]
Changed to launchQueryLIbrary.
