### ISSUE TITLE
Syntax highlighting doesn't always work

### ISSUE THREAD

**Issue by schuemie** [EHDEN/QueryLibrary#17]
![syntax](https://user-images.githubusercontent.com/6713328/59748001-7cdc7980-927a-11e9-9779-7bc45f816b8d.PNG)
As shown in the attached screenshot, syntax highlighting doesn't always work. 

The issue is hard to reproduce, as the same query sometimes works fine, and sometimes it doesn't.

**Comment by PRijnbeek** [comment]
I can confirm this behaviour and looked at it earlier but could not find the reason. Might be something deeper in Shiny or we may need to enforce a refresh of the ui programmatically in some way.

**Comment by PRijnbeek** [comment]
Using a different method now it seems to be better...
