### ISSUE TITLE
CE03 Min/max, average length of condition stratified by age/gender

### ISSUE THREAD

**Issue by PRijnbeek** [EHDEN/QueryLibrary#2]
@AnthonyMolinaro when i run this query and some of the other CE i still get this error:

Error executing SQL: com.microsoft.sqlserver.jdbc.SQLServerException: Operand data type date is invalid for subtract operator.

Does this work well on your side?

**Comment by AnthonyMolinaro** [comment]
@PRijnbeek 

Hey Peter, I'm familiar with this error.  I was doing all my testing on our redshift databases.  Binary operators like + and - are overloaded to work on some rdbms like pg and oracle and not others (like sql server).  I'll update this today.  I'll also rerun all the changes I made against pdw to make sure they are sql server friendly.

**Comment by AnthonyMolinaro** [comment]
@PRijnbeek 

Just pushed the fixes for CE01, CE03, and CE06, they worked fine on pdw.  Let me know how they look on your end.

**Comment by PRijnbeek** [comment]
They run without any error but only CE06 gives something back on Synpuf. Maybe we should select in all queries concept_ids that are available in Synpuf?

**Comment by AnthonyMolinaro** [comment]
@PRijnbeek 

Ok, I have a synpuf db to test against! : )

So, starting with CE01, if I comment out the following line I get rows:

WHERE era.condition_era_start_date > cast('01-jan-2015' as date) 

In the original code it was 2011, but I don't think we need it at all (later we might, as we go into performance tuning).  I've pushed the updated version without that predicate.

For CE03, I'm now using snomed concept code 359817006 and I get rows.  I'll go through rest of the queries to make sure I get results on synpuf.
