### ISSUE TITLE
Drug queries review

### ISSUE THREAD

**Issue by MaximMoinat** [EHDEN/QueryLibrary#20]
While solving the issues raised by Martijn (#18&#19), I noticed that the drug queries need review. For example query [D07](https://github.com/EHDEN/QueryLibrary/blob/master/inst/shinyApps/QueryLibrary/queries/drug/D07_Find_single_ingredient_drugs_by_ingredient.md) references the 'FDB' vocabulary for indications. This is a licensed vocabulary and to my knowledge not a standard vocabulary. We should adapt or remove these queries.

**Comment by PRijnbeek** [comment]
I do not really see in the query where that reference is used. Maybe just remove it in the text?

**Comment by MaximMoinat** [comment]
Removed the text referencing the FDB vocabulary in query D07.
