### ISSUE TITLE
HELP needed: Some queries don't work on Oracle

### ISSUE THREAD

**Issue by bmosseveld** [EHDEN/QueryLibrary#22]
Dear Anthony,

All queries are working on SQL Server and PostgreSQL. The folowing queries however, are not working on Oracle:

CE16, CE17, CO12, CO13, CO15, CO17, OP10, OP11, OP13

Could you please take a look at them and solve the errors?

Kind regards,

Mees

**Comment by AnthonyMolinaro** [comment]
@bmosseveld 

Hi Mees,

I looked at the Oracle sql doc and it states that they use STDDEV (with two D's) for standard deviation.  I thought that could be the source of error, but when I ran some of these queries through SqlRender, it correctly converts STDEV to STDDEV.  

I don't have an Oracle db handy, do you happen to have any error messages?  

Thanks,
  Anthony

**Comment by PRijnbeek** [comment]
@bmosseveld can you share the OHDSI Oracle test dbs credentials by email with him

**Comment by bmosseveld** [comment]
@AnthonyMolinaro 

Hi Anthony,

The errors are:

CE16	"Error executing SQL:
java.sql.SQLSyntaxErrorException: ORA-00923: FROM keyword not found where expected

CE17	"Error executing SQL:
java.sql.SQLSyntaxErrorException: ORA-00923: FROM keyword not found where expected

CO12	"Error executing SQL:
java.sql.SQLSyntaxErrorException: ORA-00936: missing expression

CO13	"Error executing SQL:
java.sql.SQLSyntaxErrorException: ORA-00923: FROM keyword not found where expected

CO15	"Error executing SQL:
java.sql.SQLSyntaxErrorException: ORA-00936: missing expression

CO17	"Error executing SQL:
java.sql.SQLSyntaxErrorException: ORA-00936: missing expression

OP10	"Error executing SQL:
java.sql.SQLSyntaxErrorException: ORA-00911: invalid character

OP11	"Error executing SQL:
java.sql.SQLDataException: ORA-01861: literal does not match format string

OP13	"Error executing SQL:
java.sql.SQLDataException: ORA-01861: literal does not match format string

I will send you the connection details for the Oracle server we use by email.

Kind regards,

Mees

**Comment by AnthonyMolinaro** [comment]
Corrected and pushed CE16 and CE17.  Working on the others, will update as I go.

**Comment by AnthonyMolinaro** [comment]
Corrected and pushed CO12.  Tested on pdw, redshift, and Oracle.

**Comment by AnthonyMolinaro** [comment]
Corrected and pushed CO13, CO15, and CO17.

**Comment by AnthonyMolinaro** [comment]
@bmosseveld, @PRijnbeek 

Done.

Corrected and pushed OP10, OP11, OP13.  Tested on Oracle, redshift, and pdw.  Please let me know how it looks on your end.

**Comment by bmosseveld** [comment]
@AnthonyMolinaro, @PRijnbeek 

Thanks Anthony!
I only had to correct OP11 and OP13 because they gave an arithmetic overflow in SQL Server on the AVG function.
