### ISSUE TITLE
NAMESPACE out of date

### ISSUE THREAD

**Issue by schuemie** [EHDEN/QueryLibrary#23]
[NAMESPACE](https://github.com/EHDEN/QueryLibrary/blob/master/NAMESPACE#L3) still lists launchSqlLibrary

Please rerun roxygen2 (or better yet, in R-Studio -> Build -> More -> Configure Build tools -> Generate documents with roxygen -> Check 'Build & Reload' 
so that roxygen2 is rerun at every build

**Comment by PRijnbeek** [comment]
fixed
