### ISSUE TITLE
Missing queries

### ISSUE THREAD

**Issue by MaximMoinat** [EHDEN/QueryLibrary#4]
We noticed that some original queries are missing in this repository. For example the [condition occurrence queries](https://github.com/EHDEN/QueryLibrary/tree/master/inst/shinyApps/QueryLibrary/queries/condition_occurence) 1 to 3, which are present on [cdmqueries.omop.org](http://cdmqueries.omop.org/condition-occurrence). Same for query [G02](https://github.com/EHDEN/QueryLibrary/tree/master/inst/shinyApps/QueryLibrary/queries/general/G02.md), which we added again.

Were these omitted on purpose?

**Comment by PRijnbeek** [comment]
No not that I am aware of, i suggest to put them back indeed
