### ISSUE TITLE
Finalize the remaining queries

### ISSUE THREAD

**Issue by PRijnbeek** [EHDEN/QueryLibrary#8]
Hi All,

Looking at the form there are still a few queries to finalise. 

@eldarallakhverdiiev you have not signed of queries yet in the [form](https://docs.google.com/spreadsheets/d/1ISMkKXfPLW7hpwhmeJ42lRg0KelNUOJOY_W7ZVw4SaA/edit#gid=1666564922) is it possible to work on this the upcoming days?

There are a few not assigned in drug_exposure section. @MaximMoinat or @tropicalberto could you possibly take these on since you already did most in this domain?

I like to run tests of all the queries before the end of this week. 

Also would be good we make a poster on the tool for the OHDSI symposium and push back to OHDSI for some feedback. Is there anyone who likes to make the poster and present it ? 

Thanks

**Comment by tropicalberto** [comment]
hi @PRijnbeek, sure, we'll take these queries
