### ISSUE TITLE
SQL Errors

### ISSUE THREAD

**Issue by PRijnbeek** [EHDEN/QueryLibrary#9]
Hi All,

@bmosseveld ran a test on sql server and we still have 60 issues to solve. The results are in a separate tab in the google sheet.

Did you all test the queries against data and did not get SQL errors before you pushed? We tested against SQL Server (in Azure).

@AnthonyMolinaro, @MaximMoinat, @eldarallakhverdiiev, @tropicalberto can you have a look at the queries you changed?

The once from EMC that still have errors are the same that were still open for discussion because these may not be useful anymore.

Thanks

**Comment by AnthonyMolinaro** [comment]
Ah yes.... those early ones.  When I started on these queries I was using ccae on redshift, then switched over to synpuf on pdw.  I'll have those fixed up today.

**Comment by eldarallakhverdiiev** [comment]
Fixed artifacts now.
I tested it against PostgreSQL (translated using SQL Render).
Found no issues except for no data on SynPuf.

**Comment by AnthonyMolinaro** [comment]
Fixed mine as well.  Test against synpuf on pdw.

**Comment by tropicalberto** [comment]
the queries assigned to the hyve are fixed as well (tested on Postgres)

**Comment by bmosseveld** [comment]
[2019-04-04 Test Result SQL Server - PostgreSQL.xlsx](https://github.com/EHDEN/QueryLibrary/files/3042488/2019-04-04.Test.Result.SQL.Server.-.PostgreSQL.xlsx)

Here are the new test results of the queries. I have tested them on SQL Server and PostgreSQL.
SQL Server gives 17 errors.
PostgreSQL gives 21 errors.
I marked the errors with colors based on the type of error.

**Comment by AnthonyMolinaro** [comment]
@bmosseveld Nice work Mees, I missed a couple.  I just corrected CE08 and DEX23 and pushed the updated version.

**Comment by bmosseveld** [comment]
I made a few small obvious corrections to errors in some queries I didn't see before.
Now it's up to the people with more SQL/CDM expertise to solve the last problems.
After runing them on SQL Server and PostgreSQL we are left with 32 errors (15 for SQL Server and 17 for PostgreSQL).
Here is the Excel sheet with the results:

[2019-04-10 Test Result SQL Server-PostgreSQL.xlsx](https://github.com/EHDEN/QueryLibrary/files/3063977/2019-04-10.Test.Result.SQL.Server-PostgreSQL.xlsx)
